version: '3.8'

services:
  mongodb:
    image: mongo:6.0.6
    container_name: mongodb-test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27017:27017
    volumes:
      - ./tmp/mongodb-test:/data/db
  postgres:
    image: postgres:15.3
    container_name: postgres-test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - 5432:5432
    volumes:
      - ./tmp/postgres-test:/var/lib/postgresql/data
